[[Python]]

Erros podem acontecer: um arquivo pode n√£o existir, permiss√µes podem faltar e codifica√ß√µes podem falhar. Por isso temos de garantir que, ainda que um erro ocorra, faremos o fechamento do nosso arquivo.

Como conseguimos lidar com erros em Python? Vamos agora falar sobre exce√ß√µes!

H√° pelo menos dois tipos de erros que podem ser destacados:¬†**erros de sintaxe e exce√ß√µes**.

## Erros de Sintaxe

Erros de sintaxe ocorrem quando o c√≥digo utiliza recursos inexistentes da linguagem que n√£o consegue interpret√°-los. √â como executar¬†`print{"Ol√°, mundo!"}`¬†em vez de¬†`print("Ol√°, mundo!")`.

## Exce√ß√µes

J√° as exce√ß√µes ocorrem durante a execu√ß√£o e resultam em mensagem de erro. Veja exemplos de exce√ß√µes:

```python
print(10 * (1 / 0))
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ZeroDivisionError: division by zero
print(4 + spam * 3)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# NameError: name 'spam' is not defined
print('2' + 2)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# TypeError: can only concatenate str (not "int") to str
```

Observe que, apenas no exemplo acima, podemos observar tr√™s exce√ß√µes:¬†`ZeroDivisionError`,¬†`NameError`¬†e¬†`TypeError`. A lista completa de exce√ß√µes j√° embutidas na linguagem pode ser vista¬†[aqui](https://docs.python.org/pt-br/3/library/exceptions.html#bltin-exceptions).

## Tratamento de exce√ß√µes

Para tratar exce√ß√µes utilizamos o conjunto de instru√ß√µes¬†`try`, com as palavras reservadas¬†`try`¬†e¬†`except`. O funcionamento dessa cl√°usula ocorre da seguinte forma:

- Se nenhuma exce√ß√£o ocorrer, a cl√°usula¬†`except`¬†√© ignorada e a execu√ß√£o da instru√ß√£o¬†`try`¬†√© finalizada.
- Se ocorrer uma exce√ß√£o durante a execu√ß√£o da cl√°usula¬†`try`, as instru√ß√µes remanescentes na cl√°usula s√£o ignoradas. Se o tipo da exce√ß√£o ocorrida tiver sido previsto em algum¬†`except`, ent√£o essa cl√°usula ser√° executada.
- Se n√£o existir nenhum tratador previsto para tal exce√ß√£o, trata-se de uma exce√ß√£o n√£o tratada e a execu√ß√£o do programa termina com uma mensagem de erro.

Vamos agora ver um exemplo de tratamento de exce√ß√µes:

```python
while True:
    try:
        x = int(input("Por favor digite um n√∫mero inteiro: "))
        break
    except ValueError:
        # 'ValueError' √© a exce√ß√£o que ocorre quando a fun√ß√£o int() recebe um
        # valor que n√£o pode ser traduzido para n√∫mero inteiro
        print("Oops! Esse n√£o era um n√∫mero inteiro. Tente novamente...")
```

Cole o c√≥digo acima no terminal interativo e teste, na pr√°tica, como funciona o tratamento de exce√ß√µes.

## Lidando com exce√ß√µes enquanto manipulamos arquivos

Vamos ver agora como podemos nos prevenir de poss√≠veis erros que ocorrem quando manipulamos arquivos. Sempre devemos fechar um arquivo e podemos, em um bloco¬†`try`, fazer isso utilizando a instru√ß√£o¬†`finally`¬†ou¬†`else`. O¬†`finally`¬†√© uma outra cl√°usula do conjunto¬†`try`, cuja finalidade √© permitir a implementa√ß√£o de a√ß√µes de limpeza, que sempre devem ser executadas independentemente da ocorr√™ncia de a√ß√µes. J√° o¬†`else`¬†ocorre sempre que todo o¬†`try`¬†for bem sucedido.

Copiar

```python
try:
    with open("arquivo.txt", "r") as file:
        print(file.read())
except FileNotFoundError:
    # ser√° executado caso haja a exce√ß√£o 'FileNotFoundError'
    print("Arquivo inexistente")
else:
    # ser√° executado se tudo ocorrer bem no try
    print("Arquivo manipulado e fechado com sucesso")
finally:
    # ser√° sempre executado, independentemente de erro
    print("Fim da tentativa de ler o arquivo")
```

Como estamos abrindo o arquivo em modo de leitura, uma exce√ß√£o ser√° levantada caso ele n√£o exista, executando as cl√°usulas¬†`except`¬†e¬†`finally`. Entretanto, se alterarmos o modo para escrita, o arquivo ser√° criado mesmo se inexistente, executando as cl√°usulas¬†`else`¬†e¬†`finally`.

## Vamos praticar um pouco?

## Exerc√≠cio 3:

Dado um arquivo contendo estudantes e suas respectivas notas, escreva um programa que:

1. l√™ todas essas informa√ß√µes;
2. aplique um filtro, mantendo somente as pessoas que est√£o reprovadas;
3. escreva seus nomes em outro arquivo.

Considere que a nota min√≠ma para aprova√ß√£o √© 6.

_Arquivo:_

```bash
Marcos 10
Felipe 4
Jos√© 6
Ana 10
Maria 9
Miguel 5
```

_Exemplo sa√≠da:_

```bash
Felipe
Miguel
```

ü¶ú A fun√ß√£o¬†`split`¬†pode ser utilizada para dividir o nome em uma linha. Ex:¬†`line.split()`¬†->¬†`["Marcos", "10"]`.

```python
recovery_students = []
with open("file.txt") as grades_file:
    for line in grades_file:
        student_grade = line
        student_grade = student_grade.split(" ")
        if int(student_grade[1]) < 6:
            recu_students.append(student_grade[0] + "\n")


with open("recuStudents.txt", mode="w") as recu_students_file:
    print(recuStudents)
    recu_students_file.writelines(recuStudents)
```

###### Fonte: [Curse](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/module/290e715d-73e3-4b2d-a3c7-4fe113474070/section/b436f9e0-dfde-4a16-9bad-82f0c559dd45/day/61e88b4a-b97a-4f96-b5a0-abaa50651e37/lesson/8ba41a24-789a-4453-8af4-1c53b5571281)
